### PR TITLE
Audit added to search for vulnerabilities

### PR DESCRIPTION
**Pull request by Cyb10101**
Little search for yarn vulnerabilities.

### CODE REVIEW

**Comment by ChrisB9** [comment]
I don't think it is necessary to include such a file into the dockerfile.
- the yarn audit is project dependend
- this does not cover dockerfile issues (which should be part of testing)
- not every system requires yarn

**Comment by Cyb10101** [comment]
That's true. I just wanted to do a simple check for vulnerabilities.

Maybe I could have made it a bit more beautiful, but I thought I'll do it another time.

I do not know if you can use that, but I left you a copy.

**Comment by Kanti** [comment]
You could simply add this to your start.sh:

````bash
     audit)
        docker-compose exec -u $USER node yarn audit
        return
        ;;
````

**Comment by Cyb10101** [comment]
This does not work because the aliases (node & yarn) are not set.

```
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"node\": executable file not found in $PATH": unknown
```
The only way I see is to create files for it.

/usr/local/bin/node_exec
```bash
#!/usr/bin/env bash
if test -S "/var/run/docker.sock"; then
  CONTAINER_ID=$(basename $(cat /proc/1/cpuset))
  DOCKER_COMPOSE_PROJECT=$(sudo docker inspect ${CONTAINER_ID} | grep '"com.docker.compose.project":' | awk '{print $2}' | tr --delete '"' | tr --delete ',')
  NODE_CONTAINER=$(sudo docker ps -f "name=${DOCKER_COMPOSE_PROJECT}_node_1" --format {{.Names}})
  sudo docker exec -u $(id -u):$(id -g) -w $(pwd) -it ${NODE_CONTAINER} "${@:1}"
else
  echo Docker not connected.
  exit 1
fi
```

/usr/local/bin/yarn
```bash
#!/usr/bin/env bash
node_exec yarn
```

That would work.
I think that's what I'm developing for myself. Should I do that here, too, if it works?

**Pull request closed without merging**
