### PR TITLE
[TASK] Improve create branches for docker

### PR DESCRIPTION
**Pull request by Cyb10101**

### CODE REVIEW

**Comment by Kanti** [comment]
@Cyb10101 please describe how this improves it

**Comment by Cyb10101** [comment]
If ever the code shifts a line, it still works.

**Comment by Kanti** [comment]
@Cyb10101 Why would the code shift a line?

**Comment by Cyb10101** [comment]
Alternatively, it eventually makes a crash. :-)

**Comment by Kanti** [comment]
@Cyb10101 I will close the PR now. If we ever encounter a Situation where the first line shifts, we will go back to it.

**Pull request closed without merging**
